# Generated by Django 4.2.7 on 2023-11-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SportEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_type', models.CharField(choices=[('', 'Select a SPORT:'), ('FOTBAL', 'Football'), ('HANDBALL', 'Handball'), ('VOLLEY', 'Volleyball'), ('GYM', 'Gymnastics'), ('TENIS', 'Tennis'), ('PING-PONG', 'Ping Pong'), ('BILIARD', 'Billiards')], max_length=255, null=True)),
                ('date', models.DateField(null=True)),
                ('ora', models.TimeField(null=True)),
                ('locatie', models.CharField(max_length=255, null=True)),
                ('status', models.BooleanField(default=False, null=True)),
                ('limit_capacity', models.IntegerField(null=True)),
            ],
        ),
    ]
