# Generated by Django 4.2.7 on 2024-01-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SportEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('sport_type', models.CharField(choices=[('', 'Select a SPORT:'), ('FOTBAL', 'Football'), ('BRAZILIAN JIU JITSU', 'Bjj'), ('MIXED MARTIAL ARTS', 'MMA'), ('KICKBOX', 'Kickbox'), ('TENIS', 'Tennis'), ('BOX', 'Box')], max_length=255, null=True)),
                ('date', models.CharField(choices=[('', 'Select a DATE:'), ('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=255, null=True)),
                ('ora', models.TimeField(null=True)),
                ('locatie', models.CharField(max_length=255, null=True)),
                ('status', models.BooleanField(default=False, null=True)),
                ('limit_capacity', models.IntegerField(null=True)),
            ],
        ),
    ]
