# Generated by Django 3.2.9 on 2023-12-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportevent',
            name='date',
            field=models.CharField(choices=[('', 'Select a DATE:'), ('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sportevent',
            name='sport_type',
            field=models.CharField(choices=[('', 'Select a SPORT:'), ('FOTBAL', 'Football'), ('BRAZILIAN JIU JITSU', 'Bjj'), ('MIXED MARTIAL ARTS', 'MMA'), ('KICKBOX', 'Kickbox'), ('TENIS', 'Tennis'), ('BOX', 'Box')], max_length=255, null=True),
        ),
    ]
