# Generated by Django 4.2.8 on 2024-01-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_events', '0002_auto_20231207_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportevent',
            name='username',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
